api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r"posts", views.PostViewSet, basename="post")
router.register(r"comments", views.CommentViewSet, basename="comment")

app_name = "api"

urlpatterns = [
    path("", include(router.urls)),
]

blog/urls.py
from django.urls import path
from blog import views
from blog.views import UserUpdateView, ContactView

app_name = "blog"

urlpatterns = [
    path("profile/update/", UserUpdateView.as_view(), name="user_update"),
    path("user/<int:pk>", views.UserDetailView.as_view(), name="user_detail"),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post"),
    path("posts/", views.PostListView.as_view(), name="posts"),
    path("my_posts/<int:pk>", views.UserPostListView.as_view(), name="my_posts"),
    path("create/", views.PostCreateView.as_view(), name="create"),
    path("update/<int:pk>", views.PostUpdateView.as_view(), name="update"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("contact_ajax/", views.contact_ajax, name="contact_ajax"),
]

core/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from blog.views import LoginUser, UserCreateView
from core import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(pattern_name="blog:posts"), name="index_redirect"),
    path("api/", include("api.urls")),
    path("admin/", admin.site.urls),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("blog/", include("blog.urls")),
    path(
        "login/",
        LoginUser.as_view(template_name="registration/login.html"),
        name="login",
    ),
]

if settings.DEBUG:
    urlpatterns += (
        [
            path("__debug__/", include("debug_toolbar.urls")),
        ]
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    photo = models.ImageField(upload_to="images/user", null=True, blank=True)

    def __str__(self):
        return self.get_full_name()


class Post(models.Model):
    title = models.CharField(max_length=70)
    description = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    is_published = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    photo = models.ImageField(upload_to="images/post", null=True, blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    pub_date = models.DateField(auto_now_add=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django.contrib.auth.forms import forms, AuthenticationForm, UserCreationForm
from blog.models import User, Post, Comment
from .models import Contact


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-input"}))
    password = forms.PasswordInput(attrs={"class": "form-input"})


class UserSignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-input",
            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "class": "form-input",
            }
        )
    )

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
        ]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "description",
            "photo",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["username"].widget.attrs.update({"class": "form-control"})
        self.fields["email"].widget.attrs.update({"class": "form-control"})
        self.fields["first_name"].widget.attrs.update({"class": "form-control"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control"})
        self.fields["description"].widget.attrs.update({"class": "form-control"})
        self.fields["photo"].widget.attrs.update({"class": "form-control"})


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "text", "photo", "is_published"]
        publish = forms.BooleanField(label="Publish now", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["title"].widget.attrs.update({"class": "form-control"})
        self.fields["description"].widget.attrs.update({"class": "form-control"})
        self.fields["text"].widget = forms.Textarea(attrs={"class": "form-control"})
        self.fields["photo"].widget.attrs.update({"class": "form-control"})


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["author", "text"]
        widgets = {
            "author": forms.TextInput(attrs={"class": "form-control"}),
            "text": forms.Textarea(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)  # Get the request object
        super().__init__(*args, **kwargs)

        if self.request and self.request.user.is_authenticated:
            full_name = self.request.user.get_full_name()
            self.fields["author"].initial = full_name
            self.fields["author"].widget.attrs["readonly"] = True
        else:
            self.fields["author"].initial = "Anonymous User"
            self.fields["author"].widget.attrs["readonly"] = False


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["first_name", "last_name", "email", "message"]
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "message": forms.Textarea(attrs={"class": "form-control"}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from .forms import UserSignUpForm, UserUpdateForm, PostForm, CommentForm, ContactForm
from blog.forms import LoginUserForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views import generic
from .models import Post, User
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.http import JsonResponse
from django.template.loader import render_to_string

from .tasks import send_contact_email


def index(request):
    return render(request, "index.html")


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = "registration/login.html"


class UserCreateView(SuccessMessageMixin, generic.CreateView):
    template_name = "registration/register.html"
    success_url = reverse_lazy("index_redirect")
    form_class = UserSignUpForm
    success_message = "Your profile was created successfully"

    def form_valid(self, form):
        super().form_valid(form)
        user = form.save(commit=False)
        user.set_password(form.cleaned_data["password1"])
        user.save()
        login(self.request, user)
        return redirect(self.get_success_url())


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = User

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        return get_object_or_404(User, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        time_on_site = timezone.now() - user.date_joined

        years_on_site = time_on_site.days // 365
        days_on_site = time_on_site.days % 365

        context["years_on_site"] = years_on_site
        context["days_on_site"] = days_on_site
        return context


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = "blog/user_form.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy("blog:user_detail", args=[self.request.user.pk])

    def form_valid(self, form):
        user = self.get_object()
        if "photo" in self.request.FILES:
            user.photo = self.request.FILES["photo"]
            user.save()
        return super().form_valid(form)


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/post_form.html"
    success_url = reverse_lazy("blog:my_posts")
    success_message = "Post created successfully!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.photo = self.request.FILES.get("photo")

        send_mail(
            "Contact Form Submission",
            f"{form.instance.author.username} has published new post"
            f"Check admin panel to approve or decline publication",
            "admin@orange.com",
            [form.instance.author.email],
            fail_silently=False,
        )
        return super().form_valid(form)

    def get_success_url(self):
        user_pk = self.object.author.pk if self.object.author else None
        if user_pk is not None:
            return reverse_lazy("blog:my_posts", kwargs={"pk": user_pk})
        else:
            return super().get_success_url()


class PostUpdateView(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blog/post_form.html"
    success_message = "Post updated successfully!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view_type"] = "update"
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        user_pk = self.object.author.pk if self.object.author else None
        if user_pk is not None:
            return reverse_lazy("blog:my_posts", kwargs={"pk": user_pk})
        else:
            return super().get_success_url()


class PostListView(generic.ListView):
    model = Post
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(is_published=True, is_approved=True).select_related("author").order_by("-pub_date")


class UserPostListView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = "blog/userpost_list.html"
    paginate_by = 5

    def get_queryset(self):
        user_pk = self.kwargs.get("pk")
        return Post.objects.select_related("author").filter(author__pk=user_pk).order_by("is_published")


class PostDetailView(generic.DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object

        comments = post.comment_set.filter(is_published=True).order_by("-pub_date")

        paginator = Paginator(comments, 3)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        form = self.form_class(request=self.request)

        context["comments"] = page_obj
        context["form"] = form

        return context

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = self.form_class(request.POST, request=request)

        if form.is_valid():
            comment = form.save(commit=False)
            if request.user.is_authenticated:
                comment.author = request.user.get_full_name()
            comment.post = post
            comment.save()

            send_mail(
                "Created new Comment",
                f"{request.user} has published new post" f"Check admin panel to approve or decline publication",
                "admin@orange.com",
                ["service@orange.com"],
                fail_silently=False,
            )

            return redirect("blog:post", pk=post.pk)

        context = self.get_context_data()
        context["form"] = form
        return self.render_to_response(context)

    def get_absolute_url(self):
        return reverse("blog:post-detail", args=[str(self.object.pk)])


class ContactView(SuccessMessageMixin, FormView):
    template_name = "contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("blog:posts")
    success_message = "Your contact request was sent successfully"

    def form_valid(self, form):
        first_name = form.cleaned_data["first_name"]
        email = form.cleaned_data["email"]
        message = form.cleaned_data["message"]

        send_mail(
            "Contact Form Submission",
            f"Name: {first_name}\nEmail: {email}\nMessage: {message}",
            "admin@orange.com",
            [email],
            fail_silently=False,
        )
        form.save()
        return super().form_valid(form)


def save_contact_form(request, form, template_name):
    data = dict()
    if request.method == "POST":
        if form.is_valid():
            form.save()

            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]

            send_contact_email.apply_async(
                kwargs={"first_name": first_name, "last_name": last_name, "email": email, "message": message},
                eta=timezone.now(),
            )
            data["form_is_valid"] = True
            data["message"] = "Your contact submitted successfully"
        else:
            data["form_is_valid"] = False

    context = {"form": form}
    data["html_form"] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def contact_ajax(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
    else:
        form = ContactForm
    return save_contact_form(request, form, "blog/contact_ajax.html")

templates/blog/contact_ajax.html
<form method="post" action={% url 'blog:contact_ajax' %} class="js-contact-create-form">
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title" id="contactModalLabel">Contact Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    <div class="modal-body" id="modal-content">
        {% include 'blog/contact_form.html' %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">CLose</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</form>

templates/blog/contact_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class+="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class+="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class+="form-control" %}
    {% endif %}
  </div>
{% endfor %}

templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}<title>{{ post.title }}</title>{% endblock %}
<body>

  {% block content %}

  <div class="featured-post single-article">
    <div class="container">
      <div class="post-slide single-page" style="background-image: url('{% if post.photo %}{{ post.photo.url }}{% else %}{% static 'blog/images/post_default.jpg' %}{% endif %}');">
        <div class="text-wrap pb-5">
          <h2 class="text-black">{{ post.title }}</h2>
          <div class="meta">
            <span>{{ post.pub_date }}</span>
          </div>
        </div>
      </div>
      <!-- .post-slide -->
    </div>
  </div>
  <div class="container article">
    <div class="row justify-content-center align-items-stretch">


      <article class="col-lg-8 order-lg-2 px-lg-5">
        <ul class="comment-list">
          <li class="comment">
            <div class="comment-body">
                <div class="vcard bio">
                    {% if post.author.photo %}
                    <img src="{{ post.author.photo.url }}" alt="Author Image" class="img-fluid rounded-circle">
                    {% else %}
                    <img src="{% static 'blog/images/user_default.png' %}" alt="Default Author Image" class="img-fluid rounded-circle">
                    {% endif %}
                </div>
              <h3><a href="{% url "blog:user_detail" pk=post.author.pk %}">{{ post.author.first_name }} {{ post.author.last_name }}</a></h3>
            </div>
          </li>
        </ul>
        <!-- END Author info -->

        {{ post.text }}


        <div class="pt-5">

          <h3 class="mb-5">{% if comments %}Comments{% else %}No Comments{% endif %}</h3>

          <!-- Add pagination links -->
          <div class="pagination">

            <span class="step-links">

              {% if comments.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ comments.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                Page {{ comments.number }} of {{ comments.paginator.num_pages }}.
              </span>

              {% if comments.has_next %}
                <a href="?page={{ comments.next_page_number }}">next</a>
                <a href="?page={{ comments.paginator.num_pages }}">last &raquo;</a>
              {% endif %}

            </span>
          </div>
          <ul class="comment-list">
            {% for comment in comments %}
              {% if comment.is_published %}
                <li class="comment">
                  <div class="comment-body">
                    {% if comment.author %}
                      {% if comment.author.strip %}
                        <h3>{{ comment.author }}</h3>
                      {% else %}
                        <h3>{{ comment.author.get_full_name }}</h3>
                      {% endif %}
                    {% else %}
                      <h3>{{ comment.author }}</h3>
                    {% endif %}
                    <div class="meta">{{ comment.pub_date }}</div>
                    <p>{{ comment.text }}</p>
                  </div>
                </li>
              {% endif %}
            {% endfor %}
          </ul>


          <!-- END comment-list -->
          <div class="comment-form-wrap pt-5">
            <h3 class="mb-5">Leave a comment</h3>
            <form action="{% url 'blog:post' post.pk %}" method="post">
              {% csrf_token %}

              {% if user.is_authenticated %}
                <div class="form-group">
                  <label for="author">Name *</label>
                  <input type="text" name="author" class="form-control" value="{{ request.user.get_full_name }}" readonly>
                </div>
              {% else %}
                <div class="form-group">
                  <label for="author">Name *</label>
                  <input type="text" name="author" class="form-control" value="{{ form.author.value }}">
                </div>
              {% endif %}

              <div class="form-group">
                <label for="message">Message</label>
                {{ form.text }}
              </div>

              <div class="form-group">
                <input type="submit" value="Post Comment" class="btn btn-primary btn-md">
              </div>
            </form>
          </div>
        </div>
      </article>
      <div class="col-md-12 col-lg-1 order-lg-1"></div>
    </div>
  </div>
  {% endblock %}
  <div id="overlayer"></div>
  <div class="loader">
    <div class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>
</body>

templates/blog/post_form.html
{% extends "base.html" %}

{% block content %}
<div class="container article">
  <div class="row justify-content-center align-items-stretch">
    <div class="col-lg-8 order-lg-2 px-lg-5">
      <div class="comment-form-wrap pt-5">
        <h3 class="text-center mb-5">{% if view_type == 'update' %}Update Post{% else %}Write a Post{% endif %}</h3>
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="{{ form.title.id_for_label }}">Title</label>
            {{ form.title }}
          </div>

          <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Description</label>
            {{ form.description }}
          </div>

          <div class="form-group">
            <label for="{{ form.text.id_for_label }}">Text</label>
            {{ form.text }}
          </div>

          <div class="form-group">
            <label for="{{ form.photo.id_for_label }}">Upload Image</label>
            {{ form.photo }}
          </div>

          <div class="form-group">
            <div class="form-check">
              <label class="form-check-label">
                {{ form.is_published }}
                Publish now
              </label>
            </div>
          </div>
          <div class="form-group text-center">
            <input type="submit" value="{% if view_type == 'update' %}Update Post{% else %}Create Post{% endif %}" class="btn btn-primary btn-md">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block title %}<title>Browse Posts</title>{% endblock %}
</head>
<body>

{% block content %}

 <div class="section-latest">
      <div class="container">
        <div class="row gutter-v1 align-items-stretch mb-5">
          <div class="col-12">
            <h2 class="section-title">Browse posts</h2>
          </div>
          <div class="col-md-9 pr-md-5">
            <div class="row">


              {% for post in post_list %}
              <div class="col-12">
                <div class="post-entry horizontal d-md-flex">
                  <div class="media">
                    <a href="#"><img src="{% if post.photo %}{{ post.photo.url }}{% else %}{% static "blog/images/post_list_post_default.png" %} {% endif %}" alt="Image" class="img-fluid"></a>
                  </div>
                  <div class="text">
                    <div class="meta">
                      <span>{{ post.pub_date }}</span>
                      <span>&bullet;</span>
                      <span><a href="{% url "blog:user_detail" pk=post.author.pk %}">{{ post.author.username }}</a></span>
                    </div>
                    <h2><a href="{% url "blog:post" pk=post.pk %}">{{ post.title }}</a></h2>
                    <p>{{ post.description }}</p>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
      </div>
    </div>

<!-- Add pagination links -->

<div class="pagination">
  <span class="step-links">
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    {% endif %}
  </span>
</div>
{% endblock %}
</div>
</body>

templates/blog/user_detail.html
{% extends "base.html" %}
{% load static %}
{% load cache %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block content %}
<div class="huge-article d-md-flex">
          <div class="img-wrap">
            <a href="#"><img src="{% if user.photo %}{% cache 500 photo %}{{ user.photo.url }}{% endcache %}{% else %}{% static 'blog/images/user_default.png' %}{% endif %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="text-wrap">
            <div class="meta">
                {% if user.is_authenticated and user == request.user %}
              <span><a href="{% url "blog:user_update" %}">Edit profile</a></span>
                {% endif %}
            </div>
            <h3>{{ user.first_name }} {{ user.last_name }}</h3>
            <p>{{ user.description }}</p>
            <div class="author d-flex align-items-center">
              <div class="text">
                <h3><a href="{% url "blog:my_posts" pk=user.pk %}">User posts</a></h3>
              </div>
            </div>
          </div>
        </div>
{% endblock %}
</body>
</html>

templates/blog/user_form.html
{% extends "base.html" %}
{% block content %}

 <div class="container article">
      <div class="row justify-content-center align-items-stretch">
        <div class="col-lg-8 order-lg-2 px-lg-5">
                <h3 class="text-center mb-5">Update Profile</h3>
                <form action="" class="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}


                  <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Username *</label>
                    {{ form.username }}
                  </div>

                  <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">Email *</label>
                    {{ form.email }}
                  </div>

                  <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">First Name</label>
                    {{ form.first_name }}
                  </div>

                  <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Last Name</label>
                    {{ form.last_name }}
                  </div>

                  <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Description</label>
                    {{ form.description }}
                  </div>

                  <div class="form-group">
                    <label for="{{ form.photo.id_for_label }}">Upload Image</label>
                    {{ form.photo }}
                  </div>

                  <div class="form-group text-center">
                    <input type="submit" value="Update Profile" class="btn btn-primary btn-md">
                  </div>
                </form>
              </div>
      </div>
 </div>
{% endblock %}

templates/blog/userpost_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="section-latest">
    <div class="container">
      <div class="row gutter-v1 align-items-stretch mb-5">
        <div class="col-12">
          <h2 class="section-title">
            {% block post-cat-unpublished %}User Posts{% endblock %}
          </h2>
        </div>
        <div class="col-md-9 pr-md-5">
          <div class="row">
            {% for post in post_list %}
            {% if post.is_approved or post.author.pk == request.user.pk %}
            <div class="col-12">
              <div class="post-entry horizontal d-md-flex">
                <div class="media">
                  <a href="#">
                    <img src="{% if post.photo %}{{ post.photo.url }}{% else %}{% static "blog/images/post_list_post_default.png" %} {% endif %}" alt="Image" class="img-fluid">
                  </a>
                </div>
                <div class="text">
                  <div class="meta">
                    <span>{{ post.pub_date }}</span>
                    <span>&bullet;</span>
                    <span><a href="{% url "blog:user_detail" pk=post.author.pk %}">{{ post.author.username }}</a></span>
                    <span>&bullet;</span>
                    <span>{% if post.is_published %}Published{% else %}Unpublished{% endif %}</span>
                    <span>&bullet;</span>
                    <span>{% if post.is_approved %}Approved{% else %}Not approved{% endif %}</span>
                  </div>
                  <h2>
                    <a href="{% url "blog:post" pk=post.pk %}">{{ post.title }}</a>
                  </h2>
                  <p>{{ post.description }}</p>
                  <p>
                      {% if post.author.pk == request.user.pk %}
                    <a href="{% url "blog:update" pk=post.pk %}">Update Post</a>
                      {% endif %}
                  </p>
                </div>
              </div>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Add pagination links -->
  <div class="pagination">
    <span class="step-links">
      {% if is_paginated %}
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">Page {{ page_obj.number }} of {{ paginator.num_pages }}.</span>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ paginator.num_pages }}">last &raquo;</a>
      {% endif %}
      {% endif %}
    </span>
  </div>
{% endblock %}