api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r"posts", views.PostViewSet, basename="post")
router.register(r"comments", views.CommentViewSet, basename="comment")

app_name = "api"

urlpatterns = [
    path("", include(router.urls)),
]

blog/urls.py
from django.urls import path
from blog import views
from blog.views import UserUpdateView, ContactView

app_name = "blog"

urlpatterns = [
    path("profile/update/", UserUpdateView.as_view(), name="user_update"),
    path("user/<int:pk>", views.UserDetailView.as_view(), name="user_detail"),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post"),
    path("posts/", views.PostListView.as_view(), name="posts"),
    path("my_posts/<int:pk>", views.UserPostListView.as_view(), name="my_posts"),
    path("create/", views.PostCreateView.as_view(), name="create"),
    path("update/<int:pk>", views.PostUpdateView.as_view(), name="update"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("contact_ajax/", views.contact_ajax, name="contact_ajax"),
]

core/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from blog.views import LoginUser, UserCreateView
from core import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(pattern_name="blog:posts"), name="index_redirect"),
    path("api/", include("api.urls")),
    path("admin/", admin.site.urls),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("blog/", include("blog.urls")),
    path(
        "login/",
        LoginUser.as_view(template_name="registration/login.html"),
        name="login",
    ),
]

if settings.DEBUG:
    urlpatterns += (
        [
            path("__debug__/", include("debug_toolbar.urls")),
        ]
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="{% static "blog/images/favicon.png" %}">

  <meta name="description" content="" />
  <meta name="keywords" content="bootstrap, bootstrap4" />


  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'blog/fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

  {% block title %}<title>Story Free HTML Template by Untree.co</title>{% endblock %}
</head>
<body>

{% block header_content %}
  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close">
        <span class="icofont-close js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>


  <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close">
          <span class="icofont-close js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <div class="container">

      <nav class="site-nav">
        <div class="row justify-content-between align-items-center">
          <div class="d-none d-lg-block col-lg-3 top-menu"></div>
          <div class="col-3 col-md-6 col-lg-6 text-lg-center logo">
            <a href="{% url "index_redirect" %}">orange<span class="text-primary">.</span> </a>
          </div>
          <div class="col-9 col-md-6 col-lg-3 text-right top-menu">
            <div class="d-inline-flex align-items-center">

              {% if user.is_authenticated %}
              <div class="search-wrap">
                <a href="{% url 'logout' %}" class="d-inline-flex align-items-center js-search-toggle">
                    <span>Log out</span>
                </a>
              </div>
              {% else %}
                 <div class="search-wrap">
                <a href="{% url 'login' %}" class="d-inline-flex align-items-center js-search-toggle">
                  <span>Login</span>
                </a>
              </div>
              {% endif %}

              <span class="mx-2 d-inline-block d-lg-none"></span>

              <a href="#" class="burger ml-3 site-menu-toggle js-menu-toggle d-inline-block d-lg-none" data-toggle="collapse" data-target="#main-navbar">
                <span></span>
              </a>
            </div>
          </div>
        </div>
        <div class="d-none d-lg-block row align-items-center py-3">

          <div class="col-12 col-sm-12 col-lg-12 site-navigation text-center">
            <ul class="js-clone-nav d-none d-lg-inline-block text-left site-menu">
              {% url "blog:posts" as posts_url %}
              {% url "blog:my_posts" pk=request.user.pk as my_posts_url  %}
              {% url 'blog:user_detail' pk=request.user.pk as user_detail_url %}
              {% url 'blog:create' as create_url %}
              {% url 'blog:contact' as contact_url %}

               <li {% if request.path == posts_url %}class="active"{% endif %}>
                 <a href="{{ posts_url }}">Browse</a>
               </li>
                {% if user.is_authenticated %}
               <li {% if request.path == my_posts_url %}class="active"{% endif %}>
                 <a href="{{ my_posts_url }}">My posts</a>
               </li>
                {% endif %}
            <li {% if request.path == create_url %}class="active"{% endif %}>
                 <a href="{{ create_url }}">Create Post</a>
               </li>
                {% if user.is_authenticated %}
               <li {% if request.path == user_detail_url %}class="active"{% endif %}>
                 <a href="{{ user_detail_url }}">Profile</a>
               </li>
                {% endif %}
            <li {% if request.path == contact_url %}class="active"{% endif %}>
                 <a href="#" class="js-create-contact" data-toggle="modal" data-url="{% url 'blog:contact_ajax' %}" data-target="contactModal">Contact Admin</a>
               </li>
            </ul>
          </div>
        </div>
      </nav> <!-- END nav -->
    </div> <!-- END container -->

{% endblock %}
{% if messages %}
  <div class="success-message">
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  </div>
{% endif %}
{% block content %}{% endblock %}

    <div class="site-footer">
      <div class="container">
        <div class="row justify-content-center copyright">

          <div class="col-lg-7 text-center">

            <div class="widget">
              <ul class="social list-unstyled">
                <li><a href="#"><span class="icon-facebook"></span></a></li>
                <li><a href="#"><span class="icon-twitter"></span></a></li>
                <li><a href="#"><span class="icon-linkedin"></span></a></li>
                <li><a href="#"><span class="icon-youtube-play"></span></a></li>
              </ul>
            </div>

            <div class="widget">
                <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> <!-- License information: https://untree.co/license/ -->
                </p>
                <p>
                    Backend by Tkach Vladyslav
                </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="overlayer"></div>
    <div class="loader">
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>


<div class="modal fade" id="modal-contact">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
</div>


{% block script %}
    <script src="{% static "blog/js/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "blog/js/popper.min.js" %}"></script>
    <script src="{% static "blog/js/bootstrap.min.js" %}"></script>
    <script src="{% static "blog/js/owl.carousel.min.js" %}"></script>
    <script src="{% static "blog/js/aos.js" %}"></script>
    <script src="{% static "blog/js/imagesloaded.pkgd.js" %}"></script>
    <script src="{% static "blog/js/isotope.pkgd.min.js" %}"></script>
    <script src="{% static "blog/js/jquery.animateNumber.min.js" %}"></script>
    <script src="{% static "blog/js/jquery.waypoints.min.js" %}"></script>
    <script src="{% static "blog/js/jquery.fancybox.min.js" %}"></script>
    <script src="{% static "blog/js/custom.js" %}"></script>
    <script src="{% static "blog/js/my_ajax.js" %}"></script>
    <script src="{% static "blog/js/ajax.js" %}"></script>
{% endblock %}
</body>
</html>

templates/contact.html
{% extends "base.html" %}
<head>
  {% block title %}<title>Contact Admin</title>{% endblock %}
</head>
<body>


  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close">
        <span class="icofont-close js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>

{% block content %}
  <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close">
          <span class="icofont-close js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    

    <div class="site-hero py-5 bg-light mb-0">

      <div class="container">
        <div class="row align-items-center justify-content-between">
          <div class="col-lg-12 text-center">
            <h1 class="text-black mb-0">Contact Us</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="section-grey bg-light">
      <div class="container">

        <div class="block">
          <div class="row justify-content-center">


            <div class="col-md-8 col-lg-8 pb-4" data-aos="fade-up" data-aos-delay="200">


              <div class="row">
                <div class="col-lg-4">
                  <div  class="service no-shadow link horizontal d-flex active" data-aos="fade-left" data-aos-delay="0">
                    <div class="service-icon color-1 mb-4">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
                      </svg>
                    </div> <!-- /.icon -->
                    <div class="service-contents">
                      <p>43 Zlatoustivska, Kyiv 393210</p>
                    </div> <!-- /.service-contents-->
                  </div> <!-- /.service -->
                </div>

                <div class="col-lg-4">
                  <div  class="service no-shadow link horizontal d-flex active" data-aos="fade-left" data-aos-delay="0">
                    <div class="service-icon color-1 mb-4">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                        <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                      </svg>
                    </div> <!-- /.icon -->
                    <div class="service-contents">
                      <p>info@orange.com</p>
                    </div> <!-- /.service-contents-->
                  </div> <!-- /.service -->
                </div>

                <div class="col-lg-4">
                  <div  class="service no-shadow link horizontal d-flex active" data-aos="fade-left" data-aos-delay="0">
                    <div class="service-icon color-1 mb-4">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                      </svg>
                    </div> <!-- /.icon -->
                    <div class="service-contents">
                      <p>+380 97 4 925 3939</p>
                    </div> <!-- /.service-contents-->
                  </div> <!-- /.service -->
                </div>
              </div>

              <form method="post">
                {% csrf_token %}
                <div class="row">
                  <div class="col-6">
                    <div class="form-group">
                      <label class="text-black" for="{{ form.first_name.id_for_label }}">First name</label>
                      {{ form.first_name }}
                    </div>
                  </div>

                  <div class="col-6">
                    <div class="form-group">
                      <label class="text-black" for="{{ form.last_name.id_for_label }}">Last name</label>
                      {{ form.last_name }}
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <label class="text-black" for="{{ form.email.id_for_label }}">Email address</label>
                  {{ form.email }}
                </div>

                <div class="form-group">
                  <label class="text-black" for="{{ form.message.id_for_label }}">Message</label>
                  {{ form.message }}
                </div>

                <button type="submit" class="btn btn-primary-hover-outline">Send Message</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}
    

    <div class="site-footer">
      <div class="container">
        <div class="row justify-content-center copyright">

          <div class="col-lg-7 text-center">
            
            <div class="widget">
              <ul class="social list-unstyled">
                <li><a href="#"><span class="icon-facebook"></span></a></li>
                <li><a href="#"><span class="icon-twitter"></span></a></li>
                <li><a href="#"><span class="icon-linkedin"></span></a></li>
                <li><a href="#"><span class="icon-youtube-play"></span></a></li>
              </ul>
            </div>

            <div class="widget">
                <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> <!-- License information: https://untree.co/license/ -->
                </p>
            </div>
          </div>
      </div>
      <div id="overlayer"></div>
      <div class="loader">
        <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</body>

templates/index.html
{% extends "base.html" %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}<title>Browse Posts</title>{% endblock %}
</head>
<body>
{#{% block content %}{% endblock %}#}
</body>
</html>